# Generated by Django 5.2.7 on 2025-11-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		("producers", "0007_plot_global_id_plot_reported_area_ha_and_more"),
	]

	operations = [
		migrations.CreateModel(
			name="Enumerator",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("document_number", models.CharField(max_length=50, unique=True)),
				("full_name", models.CharField(blank=True, max_length=200)),
				("phone", models.CharField(blank=True, max_length=25)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
			],
		),
		migrations.CreateModel(
			name="Survey",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("global_id", models.CharField(max_length=64, unique=True)),
				("census_date", models.DateTimeField()),
				("creation_date", models.DateTimeField(blank=True, null=True)),
				("edit_date", models.DateTimeField(blank=True, null=True)),
				("reported_area_ha", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
				("cocoa_area_ha", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
				("buyer", models.CharField(blank=True, max_length=200)),
				("crops", models.CharField(blank=True, max_length=200)),
				("other_crop", models.CharField(blank=True, max_length=200)),
				("insai_registered", models.CharField(blank=True, max_length=50)),
				("has_rubber", models.CharField(blank=True, max_length=50)),
				("training_received", models.CharField(blank=True, max_length=100)),
				("varieties", models.CharField(blank=True, max_length=200)),
				("plant_origin", models.CharField(blank=True, max_length=100)),
				("other_origin", models.CharField(blank=True, max_length=200)),
				("cultural_practices", models.CharField(blank=True, max_length=200)),
				("other_practice", models.CharField(blank=True, max_length=200)),
				("fertilizers", models.CharField(blank=True, max_length=200)),
				("pesticides", models.CharField(blank=True, max_length=200)),
				("pest_issues", models.CharField(blank=True, max_length=200)),
				("harvest_volume", models.IntegerField(blank=True, null=True)),
				("cocoa_plants", models.IntegerField(blank=True, null=True)),
				("plant_spacing", models.CharField(blank=True, max_length=100)),
				("families_supported", models.IntegerField(blank=True, null=True)),
				("seniors", models.IntegerField(blank=True, null=True)),
				("adults", models.IntegerField(blank=True, null=True)),
				("teens", models.IntegerField(blank=True, null=True)),
				("children", models.IntegerField(blank=True, null=True)),
				("female_total", models.IntegerField(blank=True, null=True)),
				("male_total", models.IntegerField(blank=True, null=True)),
				("highest_education", models.CharField(blank=True, max_length=100)),
				("workers_total", models.IntegerField(blank=True, null=True)),
				("workers_men", models.IntegerField(blank=True, null=True)),
				("workers_women", models.IntegerField(blank=True, null=True)),
				("workers_teens", models.IntegerField(blank=True, null=True)),
				("workers_children", models.IntegerField(blank=True, null=True)),
				("health_condition", models.CharField(blank=True, max_length=100)),
				("other_disease", models.CharField(blank=True, max_length=200)),
				("observations", models.TextField(blank=True)),
				("risk_eudr", models.CharField(blank=True, max_length=50)),
				("raw_properties", models.JSONField(blank=True, default=dict)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("enumerator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="surveys", to="surveys.enumerator")),
				("plot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="surveys", to="producers.plot")),
				("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="surveys", to="producers.producer")),
			],
			options={
				"ordering": ("-census_date",),
			},
		),
	]
