# Generated by Django 5.2.7 on 2025-10-31 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("document_type", models.CharField(max_length=20)),
                ("document_number", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField()),
                ("municipality", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "eudr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("validated", "Validado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("eudr_validation_date", models.DateTimeField(null=True)),
                ("eudr_justification", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eudr_validated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("area_hectares", models.DecimalField(decimal_places=2, max_digits=10)),
                ("polygon_geojson", models.JSONField()),
                ("centroid_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("centroid_lon", models.DecimalField(decimal_places=7, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("eudr_compliant", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producers.producer",
                    ),
                ),
            ],
        ),
    ]
