# Generated by Django 5.2.7 on 2025-11-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producer",
            name="eudr_justification",
        ),
        migrations.RemoveField(
            model_name="producer",
            name="eudr_status",
        ),
        migrations.RemoveField(
            model_name="producer",
            name="eudr_validated_by",
        ),
        migrations.RemoveField(
            model_name="producer",
            name="eudr_validation_date",
        ),
        migrations.AddField(
            model_name="producer",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Pending Review", "Pending Review"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending Review",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="producers.producer",
                    ),
                ),
            ],
        ),
    ]
