# Generated by Django 5.2.7 on 2025-11-03 13:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="centroid_lat",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="centroid_lon",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="polygon_geojson",
        ),
        migrations.AddField(
            model_name="plot",
            name="polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="eudr_validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="eudr_validation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
