# Generated by Django 5.2.7 on 2025-11-03 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_remove_plot_centroid_lat_remove_plot_centroid_lon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='eudr_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plot',
            name='plot_code',
            field=models.CharField(default='DEFAULT', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
