# Generated by Django 5.2.7 on 2025-11-04 18:07

import producers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_add_polygon_column'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "IF COL_LENGTH('producers_plot', 'polygon_geojson') IS NULL "
                        "BEGIN "
                        "    IF COL_LENGTH('producers_plot', 'polygon') IS NOT NULL "
                        "        EXEC sp_rename 'producers_plot.polygon', 'polygon_geojson', 'COLUMN'; "
                        "    ELSE "
                        "        ALTER TABLE [producers_plot] ADD [polygon_geojson] nvarchar(max) NULL; "
                        "END"
                    ),
                    reverse_sql=(
                        "IF COL_LENGTH('producers_plot', 'polygon') IS NULL "
                        "    AND COL_LENGTH('producers_plot', 'polygon_geojson') IS NOT NULL "
                        "BEGIN "
                        "    EXEC sp_rename 'producers_plot.polygon_geojson', 'polygon', 'COLUMN'; "
                        "END"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "IF COL_LENGTH('producers_plot', 'polygon_geojson') IS NOT NULL "
                        "    ALTER TABLE [producers_plot] ALTER COLUMN [polygon_geojson] nvarchar(max) NULL"
                    ),
                    reverse_sql=(
                        "IF COL_LENGTH('producers_plot', 'polygon_geojson') IS NOT NULL "
                        "    ALTER TABLE [producers_plot] ALTER COLUMN [polygon_geojson] nvarchar(max) NULL"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='plot',
                    name='polygon',
                    field=models.JSONField(
                        blank=True,
                        null=True,
                        db_column='polygon_geojson',
                        validators=[producers.models.validate_geojson],
                    ),
                ),
            ],
        ),
    ]
