# Generated by Django 5.2.7 on 2025-11-04 13:55

import producers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0003_auto_20251103_0630"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="polygon",
            field=models.JSONField(
                blank=True, null=True, validators=[producers.models.validate_geojson]
            ),
        ),
    ]
