# Generated by Django 5.2.7 on 2025-11-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0006_align_centroid_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='global_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='reported_area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='community',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='compliance_status',
            field=models.CharField(choices=[('Approved', 'Aprobado'), ('Pending Review', 'Pendiente por revisar'), ('Rejected', 'Rechazado')], default='Pending Review', max_length=20),
        ),
        migrations.AlterField(
            model_name='producer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producer',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
