# Generated by Django 5.2.7 on 2025-11-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("infrastructure", "0001_initial"),
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100, unique=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "eudr_compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("pending", "Pending"),
                            ("non_compliant", "Non-Compliant"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="producers.plot"
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="producers.producer",
                    ),
                ),
                (
                    "warehouse_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.warehouse",
                    ),
                ),
            ],
        ),
    ]
