# Generated by Django 5.2.7 on 2025-10-31 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("infrastructure", "0001_initial"),
        ("producers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100, unique=True)),
                ("batch_type", models.CharField(max_length=50)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quality_grade", models.CharField(blank=True, max_length=50)),
                (
                    "eudr_status",
                    models.CharField(
                        choices=[
                            ("eligible", "Apto"),
                            ("pending", "Pendiente"),
                            ("non_compliant", "No Conforme"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_field", "En Finca"),
                            ("in_transit", "En Tránsito"),
                            ("in_warehouse", "En Almacén"),
                            ("consolidated", "Consolidado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_consolidated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.warehouse",
                    ),
                ),
                (
                    "origin_plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="producers.plot"
                    ),
                ),
                (
                    "origin_producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="producers.producer",
                    ),
                ),
                (
                    "parent_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.batch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_id", models.CharField(max_length=100, unique=True)),
                ("origin_type", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_transit", "En Tránsito"),
                            ("received", "Recibido"),
                            ("cancelled", "Cancelado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dispatch_date", models.DateTimeField()),
                ("received_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.batch",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_in",
                        to="infrastructure.warehouse",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="infrastructure.warehouse",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.vehicle",
                    ),
                ),
            ],
        ),
    ]
