# Generated by Django 5.2.7 on 2025-11-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_remove_producer_eudr_justification_and_more'),
        ('infrastructure', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_type',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='is_consolidated',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='origin_producer',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='origin_plot',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='parent_batch',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='quality_grade',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='batch',
            name='eudr_compliance_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('pending', 'Pending'), ('non_compliant', 'Non-Compliant')], default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='plot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producers.plot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producers.producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='warehouse_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.warehouse'),
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
