# Generated by Django 5.2.7 on 2025-11-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20251103_0631'),
    ]

    operations = []
