# Generated by Django 5.2.7 on 2025-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_batch_eudr_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='eudr_status',
        ),
        migrations.AlterField(
            model_name='batch',
            name='eudr_compliance_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('pending', 'Pending'), ('non_compliant', 'Non-Compliant')], default='pending', max_length=20),
        ),
    ]
