# Generated by Django 5.2.7 on 2025-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DueDiligenceStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_id", models.CharField(max_length=100, unique=True)),
                ("producer_data", models.JSONField()),
                ("plot_polygon", models.JSONField()),
                ("chain_of_custody", models.JSONField()),
                ("pdf_file", models.FileField(upload_to="eudr_statements/")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("submitted", "Presentado"),
                            ("approved", "Aprobado"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EUDRStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("justification", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
